name: Create Release APK

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout src code
        uses: actions/checkout@v4

      - name: Install JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Allow permission for Gradle
        run: chmod +x gradlew

      - name: Build APK (Release)
        run: ./gradlew assembleRelease --stacktrace --no-daemon

      - name: Rename and Collect APKs
        run: |
          mkdir -p release-apks
          cp app/build/outputs/apk/release/app-release.apk release-apks/SimpleReader-${{ github.ref_name }}.apk

      - name: Create Release on GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: release-apks/*.apk
          name: Release ${{ github.ref_name }}
          body: |
            Automatic version release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}